spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/insurance
    username: db-user
    password: db-password
  jackson:
    default-property-inclusion: non_null
  docker:
    compose:
      lifecycle-management: start_only

logging:
  level:
    de.insurance.vehiclepricing: debug
